%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\fkuhn\Dropbox\Binghamton\teaching\Adv Macro 2\problem sets\ProblemSet6BayesianEstimation\card.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/11/30 10:58:11

%% Initialize variables.
filename = 'C:\Users\fkuhn\Dropbox\Binghamton\teaching\Adv Macro 2\problem sets\ProblemSet6BayesianEstimation\card.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column4: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column32: double (%f)
%	column33: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%*s%*s%*s%*s%*s%*s%*s%f%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
educ = dataArray{:, 1};
black = dataArray{:, 2};
smsa = dataArray{:, 3};
south = dataArray{:, 4};
exper = dataArray{:, 5};
lwage = dataArray{:, 6};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;